Repository mrsparkle-70/Emotion-detection-using-JS, pull requests merged in 2023-02, with the labels that each got.

#16 Added nav bar
  index.html
  script.js
Labels: jwoc, medium

#15 added css file
  index.css
  index.html
Labels: easy

#26 Title changed
  index.html
Labels: jwoc, easy

#30 Favicon added
  .vscode/jsconfig.json
  .vscode/main.js
  .vscode/settings.json
  favicon.ico
  index.html
Labels: jwoc, easy

#32 Dark Mode Indicator Alignment
  index.html
Labels: jwoc, easy

#33 Feature
  Input_Form_CSS/style.css
  Input_Form_CSS/style.css.map
  Input_Form_CSS/style.scss
  index.html
  script.js
Labels: jwoc, medium

#37 Footer Issue Solved
  index.html
Labels: good first issue, JWOC, easy

#38 Readme.md File Added
  README.md
Labels: JWOC, medium

#43 added option for face detection in uploaded image
  image.html
  image.js
  index.html
Labels: JWOC, medium

#49 Preloader Addition
  index.html
Labels: JWOC, easy

#51 Changed emotions from Probability to Percentage(%)
  face-api.min.js
Labels: JWOC, medium

#52 Added Webcam Toggle-Switch
  index.html
  pow-button.png
  script.js
Labels: JWOC, medium

#54 #53 issue : Added Animated Landing Page
  landing.html
  landing.js
Labels: JWOC, hard

#59 Fixed faceApi.js bugs on Responsive UI
  index.css
  index.html
  script.js
Labels: JWOC, easy
