Repository mrsparkle-70/Emotion-detection-using-JS, pull requests merged in 2023-03, with the labels that each got.

#61 Styles added to Similarty.html
  similarity.html
  similarity.js
Labels: JWOC, medium

#65 [Bugfix] Displayed Face Similarity in DOM
  similarity.html
  similarity.js
Labels: JWOC, easy

#66 Added customized Scrollbar
  index.css
Labels: JWOC, medium

#67 Issue #64
  index.css
  index.html
Labels: JWOC, medium

#74 Added testimonial
  images/face1.jpeg
  images/face2.jpeg
  images/face3.jpeg
  images/face4.jpeg
  images/face5.jpeg
  images/face6.jpeg
  images/face7.jpeg
  images/face8.jpeg
  images/face9.jpeg
  index.html
  swiper-bundle.min.css
  swiper-bundle.min.js
  testimonial.css
  testimonial.html
  testimonial.js
Labels: JWOC, easy

#76 Issue #75
  similarity.html
  testimonial.html
Labels: JWOC, easy

#78 Testimonial UI
  README.md
  testimonial.css
  testimonial.html
Labels: JWOC, medium

#79 [Bugfix] Optimization of footer
  index.css
  index.html
  similarity.html
  testimonial.html
Labels: JWOC, medium

#83 Issue #82
  testimonial.css
Labels: JWOC, medium

#85 [Feature] Added Form-Submit Enhancement
  index.html
  similarity.html
  testimonial.html
Labels: JWOC, hard

#90 Added Form for Database Management
  src/css/index.css
  src/index.html
  src/similarity.html
Labels: JWOC, hard

#92 Contact Page
  src/contact.html
  src/css/contact.css
  src/images/contact.png
  src/index.html
  src/js/contact.js
  src/similarity.html
  src/testimonial.html
Labels: JWOC, medium

#91 [Enhancement] Redesigned Upload Page
  src/js/uploadPic.js
  src/uploadPic.html
Labels: JWOC, medium

#96 Language Translator
  src/contact.html
  src/css/translate.css
  src/index.html
  src/js/translate.js
  src/similarity.html
  src/testimonial.html
Labels: JWOC, hard

#98 Added validation check
  src/contact.html
  src/index.html
  src/similarity.html
  src/testimonial.html
Labels: JWOC, medium

#97 MongoDB Setup for the Project
  database/db.js
  database/model/schema.js
  package-lock.json
  package.json
  server.js
  src/index.html
  src/similarity.html
Labels: JWOC, hard

#103 Added Script to Dump MongoDB contents to Repository
  database/dump.js
  package.json
Labels: JWOC, medium

#104 FAQ Added
  src/contact.html
  src/css/faq.css
  src/faq.html
  src/index.html
  src/similarity.html
  src/testimonial.html
  src/uploadPic.html
Labels: JWOC, medium

#106 Added Error Page
  .htaccess
  404.html
  src/css/error.css
  src/images/bugError.svg
  src/js/error.js
  src/js/scrollreveal.min.js
Labels: JWOC, hard

#108 [Enhancement] Added Form Submit Endpoint
  src/contact.html
Labels: JWOC, medium

#110 comitted changes
  README.md
  src/css/index.css
Labels: JWOC, medium

#113 Render-Deployment
  README.md
Labels: JWOC, hard
